site_name: Annals of Disco
site_url: https://skywarth.github.io/annals-of-disco/
repo_url: https://github.com/skywarth/annals-of-disco
#edit_uri: 'edit/master/docs/'


#Source: https://github.com/jobindjohn/obsidian-publish-mkdocs, Thank you

site_dir: static_site
copyright: Built with <b><u>hate</u></b> &#x1F9E1;. Use it to your heart's content, FOSS FTW. </br>  Copyright 2020 - 2024 Skywarth. All rights reserved.
extra:
  social:
      - icon: fontawesome/brands/github
        link: https://github.com/skywarth
      - icon: simple/githubsponsors
        link: https://github.com/sponsors/skywarth
      - icon: simple/buymeacoffee
        link: https://buymeacoffee.com/skywarth
theme:
    name: 'material'
    custom_dir: assets/static
    locale: en
    logo: logo.png
    favicon: logo.png
    features:
      - navigation.footer
      - content.action.view
      - toc.follow
      #- toc.integrate
      - navigation.top
    palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode


# Extensions
markdown_extensions:
  - footnotes
  # - attr_list
  - pymdownx.arithmatex:
      generic: true
  # - pymdownx.superfences
  # - pymdownx.details
  # - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - toc:
      permalink: true

plugins:
  - search
  #customs START
  - git-revision-date-localized:
      enable_creation_date: true
  - social
  #customs END
  - roamlinks
  ##- blog
  - rss

extra_javascript:
  #
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - js/tablesort.js
  #
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js 
